config/routes.rb
Rails.application.routes.draw do

  root to: 'visitors#index'
  devise_for :users, controllers: {registrations: 'registrations'}                                
  resources :users
  
  resources :reservations
  resources :restaurants do
    resources :coupons
  end
  resources :attachments
    
  namespace :admin do
    resources :users
    resources :coupons
    resources :favorites
    resources :operationtimes
    resources :reservations
    resources :restaurants
    resources :attachments
    resources :cuisines
    root to: "users#index"
  end

end

app/models/attachment.rb
class Attachment < ApplicationRecord
	mount_uploader :image, ImageUploader
  belongs_to :restaurant
end

app/controllers/admin/attachments_controller.rb
module Admin
  class AttachmentsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Attachment.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Attachment.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :set_attachment, only: [:show, :edit, :update, :destroy]
  before_action :admin_owner_only, except: [:show]

  # GET /attachments
  # GET /attachments.json
  def index
    @attachments = Attachment.all
  end

  # GET /attachments/1
  # GET /attachments/1.json
  def show
  end

  # GET /attachments/new
  def new
    @attachment = Attachment.new
  end

  # GET /attachments/1/edit
  def edit
  end

  # POST /attachments
  # POST /attachments.json
  def create
    @attachment = Attachment.new(attachment_params)

    respond_to do |format|
      if @attachment.save
        format.html { redirect_to @attachment, notice: 'Attachment was successfully created.' }
        format.json { render :show, status: :created, location: @attachment }
      else
        format.html { render :new }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attachments/1
  # PATCH/PUT /attachments/1.json
  def update
    respond_to do |format|
      if @attachment.update(attachment_params)
        format.html { redirect_to @attachment.restaurant, notice: 'Attachment was successfully updated.' }
        format.json { render :show, status: :ok, location: @attachment }
      else
        format.html { render :edit }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attachments/1
  # DELETE /attachments/1.json
  def destroy
    @attachment.destroy
    respond_to do |format|
      format.html { redirect_to attachments_url, notice: 'Attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attachment
      @attachment = Attachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attachment_params
      params.require(:attachment).permit(:restaurant_id, :image)
    end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/views/attachments/_form.html.erb
<%= image_tag @attachment.image %>
<%= simple_form_for(@attachment) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/attachments/edit.html.erb
<h1>Editing Attachment</h1>

<%= render 'form', attachment: @attachment %>

<%= link_to 'Show', @attachment %> |
<%= link_to 'Back', attachments_path %>

app/views/attachments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Attachments</h1>

<table>
  <thead>
    <tr>
      <th>Restaurant</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attachments.each do |attachment| %>
      <tr>
        <td><%= attachment.restaurant_id %></td>
        <td><%= attachment.image %></td>
        <td><%= link_to 'Show', attachment %></td>
        <td><%= link_to 'Edit', edit_attachment_path(attachment) %></td>
        <td><%= link_to 'Destroy', attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attachment', new_attachment_path %>

app/views/attachments/new.html.erb
<h1>New Attachment</h1>

<%= render 'form', attachment: @attachment %>

<%= link_to 'Back', attachments_path %>

app/views/attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Restaurant:</strong>
  <%= @attachment.restaurant_id %>
</p>

<p>
  <strong>Image:</strong>
  <%= @attachment.image %>
</p>

<%= link_to 'Edit', edit_attachment_path(@attachment) %> |
<%= link_to 'Back', attachments_path %>