config/routes.rb
Rails.application.routes.draw do

  root to: 'visitors#index'
  devise_for :users, controllers: {registrations: 'registrations'}                                
  resources :users
  
  resources :reservations
  resources :restaurants do
    resources :coupons
  end
  resources :attachments
    
  namespace :admin do
    resources :users
    resources :coupons
    resources :favorites
    resources :operationtimes
    resources :reservations
    resources :restaurants
    resources :attachments
    resources :cuisines
    root to: "users#index"
  end

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
	default_scope { order ({ name: :asc }) }

	extend FriendlyId
	friendly_id :name, use: :slugged

	mount_uploaders :images, ImageUploader
	has_many :attachments
	accepts_nested_attributes_for :attachments
	
	has_many :favorites
	has_many :users, through: :favorites
	has_many :reservations
	has_many :coupons
	accepts_nested_attributes_for :coupons
	has_one :category
	
	has_many :cuisine_memberships
	has_many :cuisines, through: :cuisine_memberships, dependent: :destroy
	
end

app/controllers/admin/restaurants_controller.rb
module Admin
  class RestaurantsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Restaurant.
    #     page(params[:page]).
    #     per(10)
    # end
   
    # Define a custom finder by overriding the `find_resource` method:
    def find_resource(param)
       Restaurant.find_by!(slug: param)
    end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  before_action :admin_owner_only, except: [:show, :index]
  before_action :restaurant_owner, except: [:show, :index, :new, :create]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @attachments = @restaurant.attachments.all
    @coupons = @restaurant.coupons.all
    @cuisines = @restaurant.cuisines.all
  end

  # GET /restaurants/new
  def new
    @restaurant = current_user.restaurants.build
    @attachment = @restaurant.attachments.build
    @coupon = @restaurant.coupons.build
    @cuisine = @restaurant.cuisines.build
    
  end

  # GET /restaurants/1/edit
  def edit
    @attachment = @restaurant.attachments.build
    @coupon = @restaurant.coupons.build
    @cuisine = @restaurant.cuisines.build
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    # @restaurant = Restaurant.new(restaurant_params)
    @restaurant = current_user.restaurants.create!(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        if(!params[:attachments].nil?)
          params[:attachments]['image'].each do |a|
            @attachment = @restaurant.attachments.create!(:image => a)
          end
        end
        flash[:success] = "Restaurant was successfully created."
        format.html { redirect_to @restaurant, notice: 'Your restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
        format.js   { render text: "window.location.href = '#{ restaurant_path @restaurant }';" }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        if(!params[:attachments].nil?)
          params[:attachments]['image'].each do |a|
            @attachment = @restaurant.attachments.create!(:image => a)
          end
        end
        flash[:success] = "Restaurant was successfully updated."
        format.html { redirect_to @restaurant, notice: 'Your restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
        format.js   { render text: "window.location.href = '#{ restaurant_path @restaurant }';" }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Your restaurant was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

    def restaurant_owner
      unless @restaurant.user_id == current_user.id or current_user.admin?
        flash[:notice] = 'Access denied, as you are not owner of this restaurant.'
        redirect_to restaurant_path
      end
  end  
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      #params.fetch(:restaurant, {})
      params.require(:restaurant).permit(:name, :address, :city, :state, :description, :zipcode, 
                                         :latitude, :longitude, :max_people, :open_time, :close_time, 
                                         :phone_number, :website_link, :max_table, :cost_range_min, 
                                         :breakfast_start, :breakfast_end, :lunch_start, :lunch_end, 
                                         :dinner_start, :dinner_end,
                                         :parking_valet, :outdoor_seating, :pet_friendly, :handicap_accessible,
                                         :smoking_allowed, :cocktails, :private_parties, :big_groups, 
                                         :cost_range_max, :location, :blurb, {images: []}, :cuisine_ids,
                                         attachments_attributes: [:id, :restaurant_id, :image],
                                         coupons_attributes: [:id, :restaurant_id, :start_date, :end_date,
                                                              :start_time, :end_time, :value, :coupon_detail,
                                                              :two_week_coupon, :month_coupon, :number, 
                                                              :monday, :tuesday, :wednesday, :thursday,
                                                              :friday, :saturday, :sunday])
    end
end

app/views/restaurants/partials/_browse.html.erb
<section class="space--sm cover imagebg height-25" data-overlay="8">
 <div class="background-image-holder"><%= image_tag "restaurant-6.jpg" %></div>
  <div class="container">
      <div class="row">
          <div class="col-sm-12s">
                  <form class="form--horizontal">
                      <div class="col-sm-2">
                          <div class="input-number">
                            <input type="number" name="quantity" placeholder="Quantity" value="2" min="1" max="12" />
                            <div class="input-number__controls">
                              <span class="input-number__increase"><i class="stack-up-open"></i></span>
                              <span class="input-number__decrease"><i class="stack-down-open"></i></span>
                            </div>
                          </div>
                      </div>
                          <div class="col-sm-3">
                                     <div class="input-select"> 
                                        <select>
                                        <option selected="selected" value="Default">Today</option>
                                        <option value="option1">Tomorrow</option>
                                        <option value="option2">Mon, Oct. 13</option>
                                        <option value="option3">Mon, Oct. 13</option>
                                        <option value="option1">Mon, Oct. 13</option>
                                        <option value="option2">Mon, Oct. 13</option>
                                        <option value="option3">Mon, Oct. 13</option>
                                        <option value="option1">Mon, Oct. 13</option>
                                        <option value="option2">Mon, Oct. 13</option>
                                        <option value="option3">Mon, Oct. 13</option>
                                        <option value="option1">Mon, Oct. 13</option>
                                        <option value="option2">Mon, Oct. 13</option>
                                        <option value="option3">Mon, Oct. 13</option>
                                        </select>
                                    </div>
                                </div>
                      <div class="col-sm-2">
                          <div class="input-select"> <select>
                            <option selected="selected" value="Default">Time?</option>
                            <option value="option1">5:00pm</option>
                            <option value="option2">5:30pm</option>
                            <option value="option3">6:00pm</option>
                            <option value="option1">6:30pm</option>
                            <option value="option2">7:00pm</option>
                            <option value="option3">7:30pm</option>
                            <option value="option1">8:00pm</option>
                            <option value="option2">8:30pm</option>
                            <option value="option3">9:00pm</option>
                            <option value="option1">9:30pm</option>
                            <option value="option2">10:00pm</option>
                            <option value="option3">10:30pm</option>
                          </select>
                        </div>
                      </div>
                        <div class="col-sm-3"> <input type="text" name="location" placeholder="Location or Restaurant"> </div>
                      <div class="col-sm-2"> <button type="submit" class="btn btn-primary type--uppercase">Find a Table</button> </div>
                  </form>
          </div>
      </div>
  </div>
</section>

<section class="space--xs bg--secondary">
    <div class="container">
        <div class="row">
          <div class="col-md-3 hidden-sm">
              <% if current_user.try(:admin?) or current_user.try(:owner?) %>
                  <i class="material-icons" style="vertical-align: middle; font-size: inherit;">add_box</i>
                  <span><%= link_to 'Add a new location', new_restaurant_path %></span>
              <% end %>
              <div class="boxed boxed--border boxed--lg bg--secondary">
                  <div class="sidebar__widget">
                    <div class="row">
                      <div class="col-sm-1">
                        <i class="material-icons">restaurant</i>
                      </div>
                      <div class="col-sm-4">
                        <span class="h5 type--uppercase">Cuisine</span>
                      </div>
                      <div class="col-sm-1">
                        <i class="material-icons text-right">map</i>
                      </div>
                      <div class="col-sm-4">
                        <span class="text-right"><%= link_to 'Map', restaurants_path('/index-map') %></span>
                      </div>
                  </div>
                <form>
                  <div class="input-checkbox">
                    <input id="checkbox1" type="checkbox" name="Mexican" />
                    <label for="checkbox2"></label>
                  </div>
                  <span>Italian (85)
                    </span>
              <br>
                <div class="input-checkbox">
                    <input id="checkbox2" type="checkbox" name="Mexican" />
                    <label for="checkbox2"></label>
                  </div>
                  <span>Mexican (102)
                    </span>
              <br>
              <div class="input-checkbox">
                <input id="checkbox1" type="checkbox" name="Mexican" />
                <label for="checkbox2"></label>
              </div>
              <span>Italian (85)
                </span>
          <br>
            <div class="input-checkbox">
                <input id="checkbox2" type="checkbox" name="Mexican" />
                <label for="checkbox2"></label>
              </div>
              <span>Mexican (102)
                </span>
        <br>
              <div class="input-checkbox">
                    <input id="checkbox1" type="checkbox" name="Mexican" />
                    <label for="checkbox2"></label>
                  </div>
                  <span>Italian (85)
                    </span>
              <br>
                <div class="input-checkbox">
                    <input id="checkbox2" type="checkbox" name="Mexican" />
                    <label for="checkbox2"></label>
                  </div>
                  <span>Mexican (102)
                    </span>
                  <span class="h6 type--uppercase text-center"><a href="#">See More</a></span>
                    <div class="row" style="padding-top:25px; border-top: 1px dotted;">
                      <div class="col-sm-1">
                        <i class="material-icons">loyalty</i>
                      </div>
                      <div class="col-sm-8">
                        <span class="h5 type--uppercase">Special Offers</span>
                      </div>

                  </div>
                <form>
                  <div class="input-checkbox">
                    <input id="checkbox1" type="checkbox" name="All Offers" />
                    <label for="checkbox2"></label>
                  </div>
                  <span>All Offers
                    </span>
              <br>
                <div class="input-checkbox">
                    <input id="checkbox2" type="checkbox" name="50% Off" />
                    <label for="checkbox2"></label>
                  </div>
                  <span>50% Off
                    </span>
              <br>
              <div class="input-checkbox">
                <input id="checkbox1" type="checkbox" name="40% Off" />
                <label for="checkbox2"></label>
              </div>
              <span>40% Off
                </span>
          <br>
            <div class="input-checkbox">
                <input id="checkbox2" type="checkbox" name="30% Off" />
                <label for="checkbox2"></label>
              </div>
              <span>30% Off
                </span>
        <br>
              <div class="input-checkbox">
                    <input id="checkbox1" type="checkbox" name="25% Off" />
                    <label for="checkbox2"></label>
                  </div>
                  <span>25% Off
                    </span>
              <br>
                <div class="input-checkbox">
                    <input id="checkbox2" type="checkbox" name="20% Off" />
                    <label for="checkbox2"></label>
                  </div>
                  <span>20% Off
                    </span>
                    <span class="h6 type--uppercase text-center"><a href="#">See More</a></span>
                    <div class="row" style="padding-top:25px; border-top: 1px dotted;">
                      <div class="col-sm-1">
                        <i class="material-icons">favorite</i>
                      </div>
                      <div class="col-sm-8">
                        <span class="h5 type--uppercase">Features</span>
                      </div>

                  </div>
                <form>
                  <div class="input-checkbox">
                    <input id="checkbox1" type="checkbox" name="Features" />
                    <label for="checkbox2"></label>
                  </div>
                  <span>All Features
                    </span>
              <br>
                <div class="input-checkbox">
                    <input id="checkbox2" type="checkbox" name="Smoking" />
                    <label for="checkbox2"></label>
                  </div>
                  <span>Smoking
                    </span>
              <br>
              <div class="input-checkbox">
                <input id="checkbox1" type="checkbox" name="Outdoor Seating" />
                <label for="checkbox2"></label>
              </div>
              <span>Outdoor Seating
                </span>
          <br>
            <div class="input-checkbox">
                <input id="checkbox2" type="checkbox" name="Dogs Allowed" />
                <label for="checkbox2"></label>
              </div>
              <span>Dogs Allowed
                </span>
        <br>
              <div class="input-checkbox">
                    <input id="checkbox1" type="checkbox" name="Big Groups" />
                    <label for="checkbox2"></label>
                  </div>
                  <span>Big Groups
                    </span>
              <br>
                <div class="input-checkbox">
                    <input id="checkbox2" type="checkbox" name="Cocktails" />
                    <label for="checkbox2"></label>
                  </div>
                  <span>Cocktails
                    </span>
                    <span class="h6 type--uppercase text-center"><a href="#">See More</a></span>
              </form>

                </div>
                  <!--end widget-->

              </div>
          </div>
          <div class="col-sm-12 col-md-8">
             
          <div class="tabs-container" data-content-align="left">
                <ul class="tabs">
                  <% if current_user.try(:admin?) or current_user.try(:owner?) %>
                  <li class="active">
                    <div class="tab__title">
                      <span class="h5">My Locations</span>
                    </div>
                    <div class="tab__content">
                      <div class="container" >
                        <% if current_user.restaurants.any? %>
                            <%= render '/restaurants/partials/restaurant_card_owner' %>
                        <% else %>
                          You have no locations yet, let's <%= link_to 'add one', new_restaurant_path %>.
                        <% end %>
                      </div>
                      <!--end of container-->
                    </div>
                  </li>
                  <li>
                  <% else %>
                  <li class="active">
                  <% end %>
                    <div class="tab__title">
                        <span class="h5">All Restaurants</span>
                      </div>
                      <div class="tab__content">
                        <div class="container" >
                          
                          <%= render '/restaurants/partials/restaurant_card' %>
                        </div>
                        <!--end of container-->
                    </div>
                  </li>
                  <li>
                    <div class="tab__title">
                      <span class="h5">Best Tables</span>
                    </div>
                    <div class="tab__content">
                      <div class="container" >
                          <%= render '/restaurants/partials/restaurant_card' %>
                      </div>
                      <!--end of container-->
                    </div>
                  </li>
                  <li>
                    <div class="tab__title">
                      <span class="h5">Best Deals</span>
                    </div>
                    <div class="tab__content">
                      <div class="container" >
                          <%= render '/restaurants/partials/restaurant_card' %>
                      </div>
                      <!--end of container-->
                    </div>
                  </li>
                </ul>
              </div><!--end of tabs container-->

        </div>
        <!--end of row-->
    </div>
    <!--end of container-->
</section>

app/views/restaurants/partials/_list_schedules.html.erb
<div>   
    <ul class="row row--list clearfix text-center">
        
        <li class="col-sm-3 col-xs-6">
            <span class="h6 type--uppercase type--fade">Open</span>
            <span class="h3">14</span>
        </li>
        <li class="col-sm-3 col-xs-6">
            <span class="h6 type--uppercase type--fade">Closed</span>
            <span class="h3">2,129</span>
        </li>
        <li class="col-sm-3 col-xs-6">
            <span class="h6 type--uppercase type--fade">Views</span>
            <span class="h3">119</span>
        </li>
        <li class="col-sm-3 col-xs-6">
                <span class="h6 type--uppercase type--fade">Favorited</span>
                <span class="h3">220</span>
        </li>
    </ul>
    <div class="text-center">
            <i class=" icon-Scissor"></i>
            <%= link_to 'Add discount', new_restaurant_coupon_path(@restaurant)%>&nbsp;&nbsp;|&nbsp;&nbsp;
            <i class="icon-Pencil"></i>
            <%= link_to 'Edit location', edit_restaurant_path(@restaurant)%>&nbsp;&nbsp;|&nbsp;&nbsp;
            <i class="icon-Calendar-4"></i>
            <%= link_to 'Open bookings', reservation_path(@restaurant)%>&nbsp;&nbsp;|&nbsp;&nbsp;
            <i class="icon-Clock-4"></i>
            <%= link_to 'Closed bookings', restaurant_path(@restaurant)%>
    </div>
    <hr>
<div>
<span class="h5 text-center">Reservation Schedule</span>
<table class="table table-striped table-condensed table-hover border-round">
    <thead>
        <tr>
            <th>
                Day
            </th>
            <th>
                Schedule
            </th>
            <th>
                Discount
            </th>
            <th>
                Max Reservations
            </th>
            <th>
            </th>
        </tr>
    </thead>
    <tbody>
        <% @restaurant.coupons.each do |coupon| %>
        <tr class="active">
            <td>
                <% if coupon.monday == true %>
                Monday<br>
                <% end %>
                <% if coupon.tuesday == true %>
                Tuesday<br>
                <% end %>
                <% if coupon.wednesday == true %>
                Wednesday<br>
                <% end %>
                <% if coupon.thursday == true %>
                Thursday<br>
                <% end %>
                <% if coupon.friday == true %>
                Friday<br>
                <% end %>
                <% if coupon.saturday == true %>
                Saturday<br>
                <% end %>
                <% if coupon.sunday == true %>
                Sunday<br>
                <% end %>
            </td>
            <td>
                <%= coupon.start_date.to_s(:time_formatted) %>-<%= coupon.end_date.to_s(:time_formatted) %>
            </td>
            <td><% if coupon.value.present? %>
                <%= coupon.value %>% Off
                <% else %>
                <% end %>
            </td>
            <td>
                <%= coupon.number %> allowed
            </td>
            <!-- <td>
            <i class="material-icons" style="vertical-align: middle; font-size: inherit;">mode_edit</i>    
            </td>
            <td>
            <i class="material-icons" style="vertical-align: middle; font-size: inherit;">mode_delete</i>    
            </td> -->
        
       
        <td><%= link_to 'Edit', edit_restaurant_coupon_path(@restaurant, coupon) %></td>
    </tr>
        <% end %>
    </tbody>
</table>
</div>

app/views/restaurants/partials/_operation_hours.html.erb
<!-- Probably add this in another sprint, as it may not be necessary -->
<h5>Hours</h5>
<section>
    <div class="row">
        <div class="col-sm-6">
            <label class="col-form-label">Monday</label>
            <%= f.time_field :breakfast_start, class: "form-control"%>
        </div>
        <div class="col-sm-6">
            <label class="col-form-label">End</label>
            <%= f.time_field :breakfast_end, class: "form-control"%>
        </div>
        <div class="col-sm-6">
            <label class="col-form-label">Tuesday</label>
            <%= f.time_field :lunch_start, class: "form-control"%>
        </div>
        <div class="col-sm-6">
            <label class="col-form-label">End</label>
            <%= f.time_field :lunch_end, class: "form-control"%>
        </div>
        <div class="col-sm-6">
            <label class="col-form-label">Wednesday</label>
            <%= f.time_field :dinner_start, class: "form-control"%>
        </div>
        <div class="col-sm-6">
            <label class="col-form-label">End</label>
            <%= f.time_field :dinner_end, class: "form-control"%>
        </div>
        <div class="col-sm-6">
            <label class="col-form-label">Thursday</label>
            <%= f.time_field :breakfast_start, class: "form-control"%>
        </div>
        <div class="col-sm-6">
            <label class="col-form-label">End</label>
            <%= f.time_field :breakfast_end, class: "form-control"%>
        </div>
        <div class="col-sm-6">
            <label class="col-form-label">Friday</label>
            <%= f.time_field :lunch_start, class: "form-control"%>
        </div>
        <div class="col-sm-6">
            <label class="col-form-label">End</label>
            <%= f.time_field :lunch_end, class: "form-control"%>
        </div>
        <div class="col-sm-6">
            <label class="col-form-label">Saturday</label>
            <%= f.time_field :dinner_start, class: "form-control"%>
        </div>
        <div class="col-sm-6">
            <label class="col-form-label">End</label>
            <%= f.time_field :dinner_end, class: "form-control"%>
        </div>
        <div class="col-sm-6">
            <label class="col-form-label">Sunday</label>
            <%= f.time_field :dinner_start, class: "form-control"%>
        </div>
        <div class="col-sm-6">
            <label class="col-form-label">End</label>
            <%= f.time_field :dinner_end, class: "form-control"%>
        </div>
        </div>
</section>

app/views/restaurants/partials/_restaurant_card_owner.html.erb
<% current_user.restaurants.each do |restaurant| %>
<div class="cta cta--horizontal text-center-xs card card-1 boxed boxed--md boxed--border">
    <div class="card__top">
        <div class="card__avatar">
            <span>
                <strong><%= link_to restaurant.name, restaurant %></strong>
            </span>
        </div>
        <div class="card__meta">
                <span class="color--primary"><strong>30% OFF</strong></span>
        </div>
    </div>
        <div class="col-sm-4">
        <%= link_to restaurant do %>
            <% restaurant.attachments.limit(1).each do |attachment| %>
            <%=image_tag attachment.image, class: "border--round", :style => "height: 130px; width: 200px; object-fit: cover; overflow: hidden;" %>
            <% end %>
        <% end %>
        </div>
        <div class="col-sm-5">
            <p>
            <%= restaurant.address %><br>
            <%= restaurant.city %>, <%= restaurant.state %> <%= restaurant.zipcode %>
            </p>
        </div>
        <div class="col-sm-3 text-right text-center-xs">
                
                <%= link_to restaurant, :class => 'btn btn--primary-1 type--uppercase' do %>
                <span class="btn__text">Bookings</span>
                <% end %>
        </div>
        <div class="card__body">
            <p><i class="material-icons">loyalty</i>
                $<%= restaurant.cost_range_min %>-<%= restaurant.cost_range_max %> per person
            </p>
        </div>
        <div class="card__bottom">
            <ul class="list-inline">
                <li>
                    <div class="card__action">
                        <a href="#">
                        <!-- <i class="material-icons">loyalty</i> -->
                            <span>$$</span>
                        </a>
                    </div>
                </li>
                <li>
                    <div class="card__action">
                        <a href="#">
                            <i class="material-icons">star</i>
                            <span>4.5/5</span>
                        </a>
                    </div>
                </li>
                <li>
                    <div class="card__action">
                        <a href="#">
                            <i class="material-icons">restaurant</i>
                            <% restaurant.cuisines.each do |cuisine| %>
                            <span><%= cuisine.name %></span>
                            <% end %>
                        </a>
                    </div>
                </li>
            <li>
            <% if current_user.try(:admin?) or current_user.try(:owner?) %>
                <div class="text-right" style="color:red;">
                    <i class="icon-Eye-2"></i>
                    <%= link_to 'View', restaurant_path(restaurant), :class=>"text-right"%>&nbsp;&nbsp;|&nbsp;&nbsp;
                    <i class="icon-Pencil"></i>
                    <%= link_to 'Edit', edit_restaurant_path(restaurant), :class=>"text-right"%>
                </div>
            <% end %>
            </li>
        </ul>
        </div>
    </div>
<% end %>